ZUser/urls.py
from django.urls import path

from . import views

app_name = 'ZUser'

urlpatterns = [
    path('', views.index, name='index'), #name= url의 별칭추가 http://localhost:8000/pybo/ 을 index
]

ZOrder_info/models.py
from django.db import models

# Create your models here.

ZSurvey_code/models.py
from django.db import models

# Create your models here.

ZSurvey_result/models.py
from django.db import models

# Create your models here.

ZUser/models.py
from django.db import models
# Create your models here.

class ZUser(models.Model):
    user_code = models.TextField()
    name = models.CharField(max_length=20)
    age = models.CharField(max_length=5)
    add_date = models.DateTimeField()
    email = models.TextField()
    
    def __str__(self):
        return self.name
    
    
    

ZUser/forms.py
from django import forms
from django.forms.fields import Field
from ZUser.models import ZUser

class UserForm(forms.ModelForm):
    class Meta:
        model = ZUser  # 사용할 모델
        fields = ['user_code', 'name']  # QuestionForm에서 사용할 Question 모델의 속성
        # widgets = {
        #     'subject': forms.TextInput(attrs={'class': 'form-control'}),
        #     'content': forms.Textarea(attrs={'class': 'form-control', 'rows': 10}),
        # }

ZOrder_info/views.py
from django.shortcuts import render

# Create your views here.

ZSurvey_code/views.py
from django.shortcuts import render

# Create your views here.

ZSurvey_result/views.py
from django.shortcuts import render

# Create your views here.

ZUser/views.py
from django.http.response import HttpResponse
from django.shortcuts import render

from ZUser.models import ZUser

# Create your views here.

def index(request):
    user_list = ZUser.objects.order_by('-add_date')
    context = {'user_list': user_list}
    return render(request, 'ZUser/user_list.html', context)

templates/ZUser/user_list.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">
<div class="container my-3">
    <table class="table">
        <thead>
        <tr class="thead-dark">
            <th>코드</th>
            <th>이름</th>
            <th>이메일</th>
            <th>등록날짜</th>
        </tr>
        </thead>
        <tbody>
        {% if user_list %}
        {% for zuser in user_list %}
        <tr>
            <td>{{ zuser.user_code }}</td>
            <td>{{ zuser.name }}</td>
            <td>{{ zuser.email }}</td>
            <td>{{ zuser.add_date }}</td>
        </tr>
        {% endfor %}
        {% else %}
        <tr>
            <td colspan="3">유저가 없습니다.</td>
        </tr>
        {% endif %}
        </tbody>
    </table>
</div>

templates/base.html
{% load static %}
<!doctype html>
<html lang="ko">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">
    <!-- pybo CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
    <title>Hello, pybo!</title>
</head>
<body>
    <!-- 네비게이션바 -->
<nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
    <a class="navbar-brand" href="{% url 'ZUser:index' %}">ZUser</a>
    <button class="navbar-toggler ml-auto" type="button" data-toggle="collapse" data-target="#navbarNav"
        aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse flex-grow-0" id="navbarNav">
        <ul class="navbar-nav">
            <li class="nav-item ">
                <a class="nav-link" href="#">로그인</a>
            </li>
        </ul>
    </div>
</nav>
<!-- 기본 템플릿 안에 삽입될 내용 Start -->
{% block content %}
{% endblock %}
<!-- 기본 템플릿 안에 삽입될 내용 End -->
</body>
</html>